using System;

namespace BinLibrary.Hook.MouseHook
{
	public enum MouseMessage
	{
		WM_LBUTTONDOWN = 513,
		WM_LBUTTONDBLCLK = 515,
		WM_LBUTTONUP = 514,
		WM_RBUTTONDOWN = 516,
		WM_RBUTTONDBLCLK = 518,
		WM_RBUTTONUP = 517,
		WM_MBUTTONDBLCLK = 521,
		WM_MBUTTONDOWN = 519,
		WM_MBUTTONUP,
		WM_XBUTTONDBLCLK = 525,
		WM_XBUTTONDOWN = 523,
		WM_XBUTTONUP,
		WM_MOUSEMOVE = 512,
		WM_MOUSEWHEEL = 522,
		WM_MOUSEHWHEEL = 526,
		WM_CAPTURECHANGED = 533,
		WM_MOUSEACTIVATE = 33,
		WM_MOUSEHOVER = 673
	}
}
